#!/bin/sh

#copy files to user home

if [ -d "/home" ]; then
    if ! [ -z "$(ls -A /home)" ]; then
        user=""
        for i in /home/*
        do
           #rm -frv "$i"/e-tahta 
        done
    fi
fi
